/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/BNKZiOdW2Qk
 */
import { AvatarImage, Avatar } from "@/components/ui/avatar";
import Link from "next/link";

export function Component() {
  return (
    <div className=" p-4 my-6 text-white flex items-center max-md:flex-col justify-center space-x-1">
      <div className="flex -space-x-2">
        <Avatar className="bg-white">
          <AvatarImage alt="User 1" src="/placeholder.svg?height=40&width=40" />
        </Avatar>
        <Avatar className="bg-white">
          <AvatarImage alt="User 2" src="/placeholder.svg?height=40&width=40" />
        </Avatar>
        <Avatar className="bg-white">
          <AvatarImage alt="User 3" src="/placeholder.svg?height=40&width=40" />
        </Avatar>
        <Avatar className="bg-white">
          <AvatarImage alt="User 3" src="/placeholder.svg?height=40&width=40" />
        </Avatar>
      </div>
      <div className="flex flex-col items-center">
        <div className="flex justify-start">
          <StarIcon className="text-yellow-400" />
          <StarIcon className="text-yellow-400" />
          <StarIcon className="text-yellow-400" />
          <StarIcon className="text-yellow-400" />
          <StarIcon className="text-yellow-400" />
        </div>

        <span className="ml-2">Trusted by 300+ users</span>
      </div>
    </div>
  );
}

function StarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="20"
      height="20"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  );
}

function XSquareIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="3" rx="2" ry="2" />
      <path d="m15 9-6 6" />
      <path d="m9 9 6 6" />
    </svg>
  );
}

function LinkedinIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  );
}
